### ISSUE TITLE
Install fails on Node 7

### ISSUE THREAD

**Issue by bhousel** [mapbox/spritezero#39]
It looks like clean installs do not work on Node 7.  There is no prebuilt mapnik binary, and the compile-from-source step fails for some reason..

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/bryan/.nvm/versions/node/v7.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/bryan/.nvm/versions/node/v7.2.0/bin/node" "/Users/bryan/.nvm/versions/node/v7.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/bryan/Projects/spritezero/node_modules/mapnik/lib/binding/node-v51-darwin-x64/mapnik.node" "--module_name=mapnik" "--module_path=/Users/bryan/Projects/spritezero/node_modules/mapnik/lib/binding/node-v51-darwin-x64"
gyp ERR! cwd /Users/bryan/Projects/spritezero/node_modules/mapnik
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by taozhi8833998** [comment]
same issue, change node version to lts version could be successful

**Comment by Neejoh** [comment]
Can't get spritezero installed either and I think I need help.

```
# ronald at iMac27.local in ~ [21:35:33]
→ npm install @mapbox/spritezero
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@mapbox/spritezero"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! Invalid name: "@mapbox/spritezero"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ronald/.npm/_logs/2017-04-10T19_35_48_221Z-debug.log
```

After reading this issue, tried downgrading to v6.10.2 but the issue keeps throwing me errors.

```
# ronald at iMac27.local in ~ [21:43:05]
→ npm install @mapbox/spritezero
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@mapbox/spritezero"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@mapbox/spritezero"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ronald/npm-debug.log
```

**Comment by pathmapper** [comment]
Tried with different node versions, but no success.

@bhousel maybe any update on this?

**Comment by bhousel** [comment]
> @bhousel maybe any update on this?

Sorry @pathmapper - I haven't been involved much in spritezero lately.
FWIW, I would not expect Node 7 to be supported, as it is not an LTS version.

**Comment by danger89** [comment]
Same problem. This is because of mapnik depedency!

mapnik@4.2.0 install: `node-pre-gyp install --fallback-to-build`

**Comment by mourner** [comment]
Looks like a stale issue since current Node LTS versions are 8, 10 and 12.
